# Site settings
title: Keith Fast
email: Keith_Fast@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://torped.github.io" # the base hostname & protocol for your site
twitter_username: Undefined
github_username:  Torped

# Build settings
markdown: kramdown
